name: Docker Nightly
on:
  workflow_dispatch:
    inputs:
      target:
        description: "Override image branch (optional)"
        type: string
        required: false

  schedule:
    - cron: "40 4 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: src/github.com/tiiuae/nats-server
          ref: ${{ inputs.target || 'main' }}

      - uses: ./src/github.com/tiiuae/nats-server/.github/actions/nightly-release
        with:
          go: "1.23"
          workdir: src/github.com/tiiuae/nats-server
          label: nightly
          hub_username: "${{ secrets.DOCKER_USERNAME }}"
          hub_password: "${{ secrets.DOCKER_PASSWORD }}"
